#!/usr/bin/env python2.7

import os
import sys
import subprocess
import argparse

def cmdline():
    parser = argparse.ArgumentParser(description='Start interactive bash shell in image or container')
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('-i', '--image', help='the name/ID of an image')
    group.add_argument('-c', '--container', help='the name/ID of a container')
    return parser.parse_known_args()

def main():
    args, other_args = cmdline()
    if args.container:
        docker_exec_cmd = "docker exec -it %s bash" % args.container
        subprocess.call(docker_exec_cmd.split())
    else:
        docker_run_cmd = ['docker', 'run', '--rm', '-i', '-t'] + other_args + ['--entrypoint=/bin/sh', args.image, '-c', '/bin/bash' ]
        subprocess.call(docker_run_cmd)
    
    # subprocess.call([ 'docker', 'run', '--rm', '-i', '-t',
    #     '--entrypoint=/bin/sh', image, '-c', '/bin/bash' ])
    

if __name__ == '__main__':
    main()
